pipeline {

agent {

}
tools { 
        maven 'MAVEN_HOME' 
       }
       
    stages {
        stage ('Compile Stage') {

            steps {
                  bat 'mvn -f Point_Pb/pom.xml clean'
               
            }
        }

        stage ('Testing Stage') {

            steps {
                  bat 'mvn -f Point_Pb/pom.xml install' 
                  }
        }

   stage ('Cucumber Reports') {

            steps {
               cucumber buildStatus: "UNSTABLE",
               fileIncludePattern: "**/cucumber.json",
               jsonReportDirectory: 'AutomationBDD/target'
                }
                
            }
                    
        }
        
            post {
        always {
            echo 'One way or another, I have finished'                       
        }
        
       success {
      emailext attachmentsPattern: '**/overview-features.html',
      body: '${SCRIPT, template="groovy-html.template"}',
      mimeType: 'text/html',
      subject: 'Success Pipeline: ${currentBuild.fullDisplayName}',
      to: 'sahoo.rashmitaqa@gmail.com'          
                         
          
        }
        failure {
          mail to: 'abhishekgaur054@gmail.com',
          subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
          body: "Something is wrong with ${env.BUILD_URL}"                
          
        } 
    }
  
}